### ISSUE TITLE
Tag docker images

### ISSUE THREAD

**Issue by ibek** [edge-of-tomorrow/cloud-bpm-grid#9]
Docker hub contains only latest images but we need to have some stable builds always available. Tag the images with version 7.0.0-SNAPSHOT, 7.1.0-SNAPSHOT, CRx, Final, etc.

**Comment by rsynek** [comment]
Images have been already pushed to docker hub. Pulling them will be made available in https://github.com/edge-of-tomorrow/cloud-bpm-grid/pull/11

**Comment by ibek** [comment]
Done as part of:
https://github.com/edge-of-tomorrow/cloud-bpm-grid/commit/09cace973c46eac9e6206ed063fb17e9058eabc1
https://github.com/edge-of-tomorrow/cloud-bpm-grid/commit/2014d57fc1afe76723a7a58dc9b9a5b81d2d3a39
